export const VENUE_SOURCES = [
  {
    id: "radio-room",
    name: "Radio Room",
    url: "https://radioroomgreenville.com/events/",
    parser: "radio-room",
    address: "28 Liberty Lane",
    city: "Greenville",
    state: "SC",
    postalCode: "29607",
    latitude: 34.8247,
    longitude: -82.3442,
    maxDetailPages: 80,
  },
  {
    id: "smileys-on-the-roxx",
    name: "Smiley's on the Roxx",
    url: "https://smileysroxx.com/greenville-downtown-smileys-on-the-roxx-music-lineup",
    parser: "calendar-page",
    address: "734 S Main Street",
    city: "Greenville",
    state: "SC",
    postalCode: "29601",
    latitude: 34.8451,
    longitude: -82.4026,
    category: "music",
  },
  {
    id: "swansons-warehouse",
    name: "Swanson's Warehouse",
    url: "https://www.swansonswarehouse.com/calendar",
    parser: "squarespace",
    address: "12 N Irvine Street",
    city: "Greenville",
    state: "SC",
    postalCode: "29601",
    latitude: 34.8545,
    longitude: -82.3987,
    maxDetailPages: 50,
  },
  {
    id: "peace-center",
    name: "Peace Center",
    url: "https://www.peacecenter.org/events",
    parser: "peace-center",
    address: "300 S Main Street",
    city: "Greenville",
    state: "SC",
    postalCode: "29601",
    latitude: 34.8477,
    longitude: -82.4018,
    maxDetailPages: 60,
  },
  {
    id: "foundry-judson-mill",
    name: "The Foundry at Judson Mill",
    url: "https://www.foundrygvl.com/events/",
    parser: "foundry",
    address: "701 Easley Bridge Road",
    city: "Greenville",
    state: "SC",
    postalCode: "29611",
    latitude: 34.8385,
    longitude: -82.4308,
  },
  {
    id: "png-downtown-alive",
    name: "PNG Downtown Alive",
    url: "https://www.greenvillesc.gov/png-downtown-alive",
    parser: "series-schedule",
    venueName: "NOMA Square",
    address: "220 N Main Street",
    city: "Greenville",
    state: "SC",
    postalCode: "29601",
    latitude: 34.8547,
    longitude: -82.3983,
    timeZone: "America/New_York",
    startTime: "17:30",
    endTime: "20:30",
    schedule: [
      { date: "2026-08-06", name: "Remember Me – Willie Nelson Tribute", genres: ["classic country", "tribute"] },
      { date: "2026-08-13", name: "Lauren Morse" },
      { date: "2026-08-20", name: "Randomonium" },
      { date: "2026-08-27", name: "Gimme the Gig Winner" },
    ],
  },
  {
    id: "greenville-heritage-main-street-fridays",
    name: "Greenville Heritage Main Street Fridays",
    url: "https://www.greenvillesc.gov/greenville-heritage-main-street-fridays",
    parser: "series-schedule",
    venueName: "NOMA Square",
    address: "220 N Main Street",
    city: "Greenville",
    state: "SC",
    postalCode: "29601",
    latitude: 34.8547,
    longitude: -82.3983,
    timeZone: "America/New_York",
    startTime: "17:30",
    endTime: "21:30",
    schedule: [
      { date: "2026-08-07", name: "Funknation", genres: ["funk", "soul", "r&b", "beach"] },
      { date: "2026-08-14", name: "Beth Inabinett & For the Funk of It" },
      { date: "2026-08-21", name: "SideCar" },
      { date: "2026-08-28", name: "Soultown Revue" },
      { date: "2026-09-04", name: "Shades of Brown" },
      { date: "2026-09-11", name: "Encore" },
      { date: "2026-09-18", name: "Hot as a Pepper" },
      { date: "2026-09-25", name: "True Blues" },
    ],
  },
];
