export const VENUE_SOURCES = [
  {
    id: "radio-room",
    name: "Radio Room",
    url: "https://radioroomgreenville.com/events/",
    city: "Greenville",
    state: "SC",
    latitude: 34.8247,
    longitude: -82.3442,
  },
  {
    id: "swansons-warehouse",
    name: "Swanson's Warehouse",
    url: "https://www.swansonswarehouse.com/calendar",
    city: "Greenville",
    state: "SC",
    latitude: 34.8545,
    longitude: -82.3987,
  },
  {
    id: "peace-center",
    name: "Peace Center",
    url: "https://www.peacecenter.org/events",
    city: "Greenville",
    state: "SC",
    latitude: 34.8477,
    longitude: -82.4018,
  },
  {
    id: "foundry-judson-mill",
    name: "The Foundry at Judson Mill",
    url: "https://www.foundrygvl.com/events/",
    city: "Greenville",
    state: "SC",
    latitude: 34.8385,
    longitude: -82.4308,
  },
];
