export const VENUE_SOURCES = [
  {
    id: "radio-room",
    name: "Radio Room",
    url: "https://radioroomgreenville.com/events/",
    parser: "radio-room",
    address: "28 Liberty Lane",
    city: "Greenville",
    state: "SC",
    postalCode: "29607",
    latitude: 34.8247,
    longitude: -82.3442,
    maxDetailPages: 80,
  },
  {
    id: "swansons-warehouse",
    name: "Swanson's Warehouse",
    url: "https://www.swansonswarehouse.com/calendar",
    parser: "squarespace",
    address: "12 N Irvine Street",
    city: "Greenville",
    state: "SC",
    postalCode: "29601",
    latitude: 34.8545,
    longitude: -82.3987,
    maxDetailPages: 50,
  },
  {
    id: "peace-center",
    name: "Peace Center",
    url: "https://www.peacecenter.org/events",
    parser: "json-ld",
    address: "300 S Main Street",
    city: "Greenville",
    state: "SC",
    postalCode: "29601",
    latitude: 34.8477,
    longitude: -82.4018,
  },
  {
    id: "foundry-judson-mill",
    name: "The Foundry at Judson Mill",
    url: "https://www.foundrygvl.com/events/",
    parser: "json-ld",
    address: "701 Easley Bridge Road",
    city: "Greenville",
    state: "SC",
    postalCode: "29611",
    latitude: 34.8385,
    longitude: -82.4308,
  },
];
